// ISO 3166-1 alpha-2 → { numeric code, English name }.
// The numeric code matches the `id` on world-atlas countries-110m geographies,
// so we can color the world choropleth from alpha-2 event counts. Numeric codes
// are compared numerically (parseInt), so leading-zero differences don't matter.
export const ISO_COUNTRIES: Record<string, { num: string; name: string }> = {
  US: { num: '840', name: 'United States' },
  CA: { num: '124', name: 'Canada' },
  GB: { num: '826', name: 'United Kingdom' },
  AU: { num: '036', name: 'Australia' },
  MX: { num: '484', name: 'Mexico' },
  AF: { num: '004', name: 'Afghanistan' },
  AL: { num: '008', name: 'Albania' },
  DZ: { num: '012', name: 'Algeria' },
  AD: { num: '020', name: 'Andorra' },
  AO: { num: '024', name: 'Angola' },
  AG: { num: '028', name: 'Antigua and Barbuda' },
  AR: { num: '032', name: 'Argentina' },
  AM: { num: '051', name: 'Armenia' },
  AT: { num: '040', name: 'Austria' },
  AZ: { num: '031', name: 'Azerbaijan' },
  BS: { num: '044', name: 'Bahamas' },
  BH: { num: '048', name: 'Bahrain' },
  BD: { num: '050', name: 'Bangladesh' },
  BB: { num: '052', name: 'Barbados' },
  BY: { num: '112', name: 'Belarus' },
  BE: { num: '056', name: 'Belgium' },
  BZ: { num: '084', name: 'Belize' },
  BJ: { num: '204', name: 'Benin' },
  BT: { num: '064', name: 'Bhutan' },
  BO: { num: '068', name: 'Bolivia' },
  BA: { num: '070', name: 'Bosnia and Herzegovina' },
  BW: { num: '072', name: 'Botswana' },
  BR: { num: '076', name: 'Brazil' },
  BN: { num: '096', name: 'Brunei' },
  BG: { num: '100', name: 'Bulgaria' },
  BF: { num: '854', name: 'Burkina Faso' },
  BI: { num: '108', name: 'Burundi' },
  CV: { num: '132', name: 'Cabo Verde' },
  KH: { num: '116', name: 'Cambodia' },
  CM: { num: '120', name: 'Cameroon' },
  CF: { num: '140', name: 'Central African Republic' },
  TD: { num: '148', name: 'Chad' },
  CL: { num: '152', name: 'Chile' },
  CN: { num: '156', name: 'China' },
  CO: { num: '170', name: 'Colombia' },
  KM: { num: '174', name: 'Comoros' },
  CG: { num: '178', name: 'Congo' },
  CD: { num: '180', name: 'Congo (DRC)' },
  CR: { num: '188', name: 'Costa Rica' },
  CI: { num: '384', name: "Côte d'Ivoire" },
  HR: { num: '191', name: 'Croatia' },
  CU: { num: '192', name: 'Cuba' },
  CY: { num: '196', name: 'Cyprus' },
  CZ: { num: '203', name: 'Czechia' },
  DK: { num: '208', name: 'Denmark' },
  DJ: { num: '262', name: 'Djibouti' },
  DM: { num: '212', name: 'Dominica' },
  DO: { num: '214', name: 'Dominican Republic' },
  EC: { num: '218', name: 'Ecuador' },
  EG: { num: '818', name: 'Egypt' },
  SV: { num: '222', name: 'El Salvador' },
  GQ: { num: '226', name: 'Equatorial Guinea' },
  ER: { num: '232', name: 'Eritrea' },
  EE: { num: '233', name: 'Estonia' },
  SZ: { num: '748', name: 'Eswatini' },
  ET: { num: '231', name: 'Ethiopia' },
  FJ: { num: '242', name: 'Fiji' },
  FI: { num: '246', name: 'Finland' },
  FR: { num: '250', name: 'France' },
  GA: { num: '266', name: 'Gabon' },
  GM: { num: '270', name: 'Gambia' },
  GE: { num: '268', name: 'Georgia' },
  DE: { num: '276', name: 'Germany' },
  GH: { num: '288', name: 'Ghana' },
  GR: { num: '300', name: 'Greece' },
  GD: { num: '308', name: 'Grenada' },
  GT: { num: '320', name: 'Guatemala' },
  GN: { num: '324', name: 'Guinea' },
  GW: { num: '624', name: 'Guinea-Bissau' },
  GY: { num: '328', name: 'Guyana' },
  HT: { num: '332', name: 'Haiti' },
  HN: { num: '340', name: 'Honduras' },
  HK: { num: '344', name: 'Hong Kong' },
  HU: { num: '348', name: 'Hungary' },
  IS: { num: '352', name: 'Iceland' },
  IN: { num: '356', name: 'India' },
  ID: { num: '360', name: 'Indonesia' },
  IR: { num: '364', name: 'Iran' },
  IQ: { num: '368', name: 'Iraq' },
  IE: { num: '372', name: 'Ireland' },
  IL: { num: '376', name: 'Israel' },
  IT: { num: '380', name: 'Italy' },
  JM: { num: '388', name: 'Jamaica' },
  JP: { num: '392', name: 'Japan' },
  JO: { num: '400', name: 'Jordan' },
  KZ: { num: '398', name: 'Kazakhstan' },
  KE: { num: '404', name: 'Kenya' },
  KI: { num: '296', name: 'Kiribati' },
  KW: { num: '414', name: 'Kuwait' },
  KG: { num: '417', name: 'Kyrgyzstan' },
  LA: { num: '418', name: 'Laos' },
  LV: { num: '428', name: 'Latvia' },
  LB: { num: '422', name: 'Lebanon' },
  LS: { num: '426', name: 'Lesotho' },
  LR: { num: '430', name: 'Liberia' },
  LY: { num: '434', name: 'Libya' },
  LI: { num: '438', name: 'Liechtenstein' },
  LT: { num: '440', name: 'Lithuania' },
  LU: { num: '442', name: 'Luxembourg' },
  MO: { num: '446', name: 'Macao' },
  MG: { num: '450', name: 'Madagascar' },
  MW: { num: '454', name: 'Malawi' },
  MY: { num: '458', name: 'Malaysia' },
  MV: { num: '462', name: 'Maldives' },
  ML: { num: '466', name: 'Mali' },
  MT: { num: '470', name: 'Malta' },
  MH: { num: '584', name: 'Marshall Islands' },
  MR: { num: '478', name: 'Mauritania' },
  MU: { num: '480', name: 'Mauritius' },
  FM: { num: '583', name: 'Micronesia' },
  MD: { num: '498', name: 'Moldova' },
  MC: { num: '492', name: 'Monaco' },
  MN: { num: '496', name: 'Mongolia' },
  ME: { num: '499', name: 'Montenegro' },
  MA: { num: '504', name: 'Morocco' },
  MZ: { num: '508', name: 'Mozambique' },
  MM: { num: '104', name: 'Myanmar' },
  NA: { num: '516', name: 'Namibia' },
  NR: { num: '520', name: 'Nauru' },
  NP: { num: '524', name: 'Nepal' },
  NL: { num: '528', name: 'Netherlands' },
  NZ: { num: '554', name: 'New Zealand' },
  NI: { num: '558', name: 'Nicaragua' },
  NE: { num: '562', name: 'Niger' },
  NG: { num: '566', name: 'Nigeria' },
  KP: { num: '408', name: 'North Korea' },
  MK: { num: '807', name: 'North Macedonia' },
  NO: { num: '578', name: 'Norway' },
  OM: { num: '512', name: 'Oman' },
  PK: { num: '586', name: 'Pakistan' },
  PW: { num: '585', name: 'Palau' },
  PS: { num: '275', name: 'Palestine' },
  PA: { num: '591', name: 'Panama' },
  PG: { num: '598', name: 'Papua New Guinea' },
  PY: { num: '600', name: 'Paraguay' },
  PE: { num: '604', name: 'Peru' },
  PH: { num: '608', name: 'Philippines' },
  PL: { num: '616', name: 'Poland' },
  PT: { num: '620', name: 'Portugal' },
  PR: { num: '630', name: 'Puerto Rico' },
  QA: { num: '634', name: 'Qatar' },
  RO: { num: '642', name: 'Romania' },
  RU: { num: '643', name: 'Russia' },
  RW: { num: '646', name: 'Rwanda' },
  KN: { num: '659', name: 'Saint Kitts and Nevis' },
  LC: { num: '662', name: 'Saint Lucia' },
  VC: { num: '670', name: 'Saint Vincent and the Grenadines' },
  WS: { num: '882', name: 'Samoa' },
  SM: { num: '674', name: 'San Marino' },
  ST: { num: '678', name: 'Sao Tome and Principe' },
  SA: { num: '682', name: 'Saudi Arabia' },
  SN: { num: '686', name: 'Senegal' },
  RS: { num: '688', name: 'Serbia' },
  SC: { num: '690', name: 'Seychelles' },
  SL: { num: '694', name: 'Sierra Leone' },
  SG: { num: '702', name: 'Singapore' },
  SK: { num: '703', name: 'Slovakia' },
  SI: { num: '705', name: 'Slovenia' },
  SB: { num: '090', name: 'Solomon Islands' },
  SO: { num: '706', name: 'Somalia' },
  ZA: { num: '710', name: 'South Africa' },
  KR: { num: '410', name: 'South Korea' },
  SS: { num: '728', name: 'South Sudan' },
  ES: { num: '724', name: 'Spain' },
  LK: { num: '144', name: 'Sri Lanka' },
  SD: { num: '729', name: 'Sudan' },
  SR: { num: '740', name: 'Suriname' },
  SE: { num: '752', name: 'Sweden' },
  CH: { num: '756', name: 'Switzerland' },
  SY: { num: '760', name: 'Syria' },
  TW: { num: '158', name: 'Taiwan' },
  TJ: { num: '762', name: 'Tajikistan' },
  TZ: { num: '834', name: 'Tanzania' },
  TH: { num: '764', name: 'Thailand' },
  TL: { num: '626', name: 'Timor-Leste' },
  TG: { num: '768', name: 'Togo' },
  TO: { num: '776', name: 'Tonga' },
  TT: { num: '780', name: 'Trinidad and Tobago' },
  TN: { num: '788', name: 'Tunisia' },
  TR: { num: '792', name: 'Türkiye' },
  TM: { num: '795', name: 'Turkmenistan' },
  TV: { num: '798', name: 'Tuvalu' },
  UG: { num: '800', name: 'Uganda' },
  UA: { num: '804', name: 'Ukraine' },
  AE: { num: '784', name: 'United Arab Emirates' },
  UY: { num: '858', name: 'Uruguay' },
  UZ: { num: '860', name: 'Uzbekistan' },
  VU: { num: '548', name: 'Vanuatu' },
  VA: { num: '336', name: 'Vatican City' },
  VE: { num: '862', name: 'Venezuela' },
  VN: { num: '704', name: 'Vietnam' },
  YE: { num: '887', name: 'Yemen' },
  ZM: { num: '894', name: 'Zambia' },
  ZW: { num: '716', name: 'Zimbabwe' },
};

export function countryNameFromA2(code: string): string {
  return ISO_COUNTRIES[code]?.name ?? code;
}
